// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBspl6MLnjPPE6aJ0GZ6YNFIWNKHmusnSs',
    appId: '1:834094387329:web:c15bf5fcd568919c4dfd80',
    messagingSenderId: '834094387329',
    projectId: 'alvian-2832d',
    authDomain: 'alvian-2832d.firebaseapp.com',
    databaseURL: 'https://alvian-2832d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alvian-2832d.firebasestorage.app',
    measurementId: 'G-QPS81FPHEB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCMrXiairEZpOEpX-85FA45mrA8liyBv8M',
    appId: '1:834094387329:android:1e92e25769888e3d4dfd80',
    messagingSenderId: '834094387329',
    projectId: 'alvian-2832d',
    databaseURL: 'https://alvian-2832d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alvian-2832d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAm6S5RxkmfR6WEkQe8tT0WlMkwUpkrrCY',
    appId: '1:834094387329:ios:4c4d3d4232546bbe4dfd80',
    messagingSenderId: '834094387329',
    projectId: 'alvian-2832d',
    databaseURL: 'https://alvian-2832d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alvian-2832d.firebasestorage.app',
    androidClientId: '834094387329-8kilkf8c87ulmrqhajk2qsaf3nsdqba1.apps.googleusercontent.com',
    iosClientId: '834094387329-08bqan1chesh5treqs81jg55s24qu2u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bisa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAm6S5RxkmfR6WEkQe8tT0WlMkwUpkrrCY',
    appId: '1:834094387329:ios:4c4d3d4232546bbe4dfd80',
    messagingSenderId: '834094387329',
    projectId: 'alvian-2832d',
    databaseURL: 'https://alvian-2832d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alvian-2832d.firebasestorage.app',
    androidClientId: '834094387329-8kilkf8c87ulmrqhajk2qsaf3nsdqba1.apps.googleusercontent.com',
    iosClientId: '834094387329-08bqan1chesh5treqs81jg55s24qu2u5.apps.googleusercontent.com',
    iosBundleId: 'com.example.bisa',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBspl6MLnjPPE6aJ0GZ6YNFIWNKHmusnSs',
    appId: '1:834094387329:web:c15bf5fcd568919c4dfd80',
    messagingSenderId: '834094387329',
    projectId: 'alvian-2832d',
    authDomain: 'alvian-2832d.firebaseapp.com',
    databaseURL: 'https://alvian-2832d-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'alvian-2832d.firebasestorage.app',
    measurementId: 'G-QPS81FPHEB',
  );
}
